name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@stockup.ddns.net << 'EOF'
            cd /home/ubuntu/stockup-backend
            sudo docker stop stockup-backend-server-1
            git pull
            sudo docker compose up --build -d --restart always
            curl -X POST ${{ secrets.SUCCESS_WEBHOOK }}
          EOF
